export const myProjects = [
    {title: "fire Blog app" , content: "this is my first full stack project, a fireblog web app using for the frontend vue.js and firebase services for the backend", category: "vue" , image: '../../assets/fireblog.png', github: "https://github.com/tarek-ait/fullstack-fireblog-web-application.git", demo:""},
    {title: "Sieve Of Eratosthenes Algorithm" , content: "This project is a collaborative effort between Rayan Derradji and Tarek Ait Ahmed for the Practical Work N°1 on Linked List. The aim of this project is to implement a search algorithm for finding prime numbers up to a specified number, using linked lists and dynamic arrays with the Sieve of Eratosthenes algorithm", category: "esi" , image: '../../public/assets/tp1.jpg', github: "https://github.com/Rennsen/TP1_ALSDD_R-T.git", demo:""},
    {title: "BST Traversals" , content: "This project, developed in collaboration with Rayan Derradji, supervised by Pr D.E Zegour, focuses on implementing and animating two types of traversals for a Binary Search Tree (BST) using the C programming language. Additionally, we have utilized the Z language, which is specific to our higher school (ESI), to complement the algorithmic aspect of this project.", category: "esi" , image: '../../public/assets/tp2.png', github: "", demo:""},
    {title: "what to do for dinner?" , content: "frontend fetching meals data,using the vue router and the meals api, we can now find recepies from all around teh world, a youtube tutorial with all the ingredients needed !", category: "vue" , image: '../../assets/meals.png', github: "https://github.com/tarek-ait/meals.git", demo:"https://meals-3b5l6gnts-tarek-aits-projects.vercel.app/"},
    {title: "Autism Bridge" , content: "this is the front-end code for our application autism-bridge , our application in the hackathon 'hackin' organized by cse in esi algiers , pretty basic but it holds the best memories with the best friends in our team", category: "htmlCss" , image: '../../assets/hackIn6.png', github: "https://github.com/tarek-ait/hackIn6.git", demo:"https://tarek-ait.github.io/hackIn6/"},
    {title: "javascript calculater" , content: "getting started with javascript !!", category: "javascript" , image: '../../assets/calculater.png', github: "https://github.com/tarek-ait/calculator.git", demo:"https://tarek-ait.github.io/calculator/"},
    {title: "Random jokes" , content: "fetching random jokes from an api", category: "javascript" , image: '../../assets/jokes.png', github: "https://github.com/tarek-ait/Random-jokes-.git", demo:"https://tarek-ait.github.io/Random-jokes-/"},
    {title: "Tresor ESI" , content: "clonnig tresor cse website with vue", category: "vue" , image: '../../assets/tresor.png', github: "https://github.com/tarek-ait/tresor-esi.git", demo:"https://tresor-z798-8vfj2xp8t-tarek-aits-projects.vercel.app/"},
    {title: "Snake game" , content: "snake game challenge using html css and javascript", category: "javascript" , image: '../../assets/snake.png', github: "https://github.com/tarek-ait/snakeGame.git", demo:"https://tarek-ait.github.io/snakeGame/"},
    {title: "tech website" , content: "dive into the use of bootstrap library in your websites ! ", category: "htmlCss" , image: '../../assets/bootstrap2.png', github: "https://github.com/tarek-ait/bootstrapFrontend2.git", demo:"https://tarek-ait.github.io/bootstrapFrontend2/"},
    {title: "Frontend Bootcamp" , content: "another challenge to dive into the use of bootstrap library in your websites ! ", category: "htmlCss" , image: '../../assets/bootstrap.png', github: "https://github.com/tarek-ait/bootstrapFrontend.git", demo:"https://tarek-ait.github.io/bootstrapFrontend/#"},
    {title: "Vuex" , content: "learn vuex through this simple counter", category: "vue" , image: '../../assets/vuex.png', github: "https://github.com/tarek-ait/VuexCounter.git", demo:""},
    {title: "NFT website" , content: "learn css styling through this website", category: "htmlCss" , image: '../../assets/nftw.png', github: "https://github.com/tarek-ait/NFTWebsite.git", demo:"https://tarek-ait.github.io/NFTWebsite/"},
    {title: "portfolio" , content: "learn css stylings making this portfolio", category: "htmlCss" , image: '../../assets/portfolio.png', github: "https://github.com/tarek-ait/Portfolio2.git", demo:"https://tarek-ait.github.io/Portfolio2/"},
    {title: "Age Calculator" , content: "frontend mentor challenge", category: "htmlCss" , image: '../../assets/age.jpg', github: "https://github.com/tarek-ait/ageCalculator.git", demo:"https://tarek-ait.github.io/ageCalculator/"},
    {title: "portfolio" , content: "learn css stylings making this portfolio", category: "htmlCss" , image: '../../assets/portfolio2.png', github: "https://github.com/tarek-ait/Portfolio1.git", demo:"https://tarek-ait.github.io/Portfolio1/"},
]


